### PR TITLE
CC update number idk

### PR DESCRIPTION
**Pull request by twinklezzzz**
# Changelog

:cl: twinkle
- add: CC UPDATE :D
- fix: Fixed missing tiles at CC
- fix: Cams actually got power :D

### CODE REVIEW

**Comment by VMSolidus** [comment]
image

Can't merge it! You need to first delete all "invalid" entries from the map's .yml file!

**Comment by twinklezzzz** [comment]
> image
> 
> Can't merge it! You need to first delete all "invalid" entries from the map's .yml file!

Ill get working on that

**Comment by twinklezzzz** [comment]
Commited something that hopefully fixes it

**Comment by twinklezzzz** [comment]
Woops did a small woopsie there

**Pull request merged**
