### PR TITLE
Adds 'PTSD'

### PR DESCRIPTION
**Pull request by BlueHNT**
## About the PR

This PR aims to add PTSD which stands for Personal Tiny Self Defense Gun. It's a small pistol intended for use by command crew to replace the need for them to take large laser rifles for basically just existing. It is inherently not very strong and it's intention is to be a shoot and run away kinda pistol with a long recharge time and few shots under it's belt.

## Why / Balance

Gives command a reason not to run to security requesting laser pistols with even the most minor danger to their life. They can instead grab a PTSD from their locker!

## Technical details

It'll add a weapon and add it to command crew lockers. 1 for each head.

## Media

image

---

:cl:
Add: Adds 'PTSD' to command heads

### CODE REVIEW

**Review by VMSolidus — CHANGES_REQUESTED** [review]
This needs to have a meta file created for the new ptsd.rsi folder, which must include a link to where the sprites were obtained. This PR also needs to address some way for the item to be obtainable in-game.

**Comment by BlueHNT** [comment]
> This needs to have a meta file created for the new ptsd.rsi folder, which must include a link to where the sprites were obtained. This PR also needs to address some way for the item to be obtainable in-game.

Ah yeah, I needed to make proof concept to know if it's worth properly making it.

**Comment by BlueHNT** [comment]
@VMSolidus 

Is there a way to make the sprites switch from `mag-unshaded-#` to `disable-mag-unshaded-#` when you switch it to `BulletDisabler` and back to normal when you switch it to `BulletEnergyGunLaser` in the `ProjectileBatteryAmmoProvider`? Since it doesn't have that kind of function.

**Comment by ScyronX** [comment]
I believe its possible to do that you can find similar functions in frontier station multiphase antique laser gun and energy gun and perhaps in deltaV too

**Comment by BlueHNT** [comment]
> I believe its possible to do that you can find similar functions in frontier station multiphase antique laser gun and energy gun and perhaps in deltaV too

It's the only real option I have without remaking the entire system ground up to be honest. The issue with it is that it is hardcoded to 3 types, which probably is enough to be honest...? But it sucks. It also seems to only change the general visualizer, not actual ammo visualizer. So you cannot replace the magazine visuals with different colored ones sadly enough!

**Pull request merged**
