### PR TITLE
New CC

### PR DESCRIPTION
**Pull request by twinklezzzz**
# Description
New Central Command map,
I Decided to make a new map for Central Command.
What's diffrent?
I added an Epistemics department so if need be central can use it (i do have to say its very barebones as they only have a robotics and a place for artifacts so no anomalies)
Added some ERT armories (Death Squad, ERT Sec, CBURN, Medical ERT and NTIA agent/sec-officers)
Medical sadly has been given a debuff in space but has all the same functionality.

# Changelog

:cl twinkle:
- add: New Central Command station

### CODE REVIEW

**Comment by twinklezzzz** [comment]
It seems like i messed up the description first time should be edited now my bad

**Comment by VMSolidus** [comment]
If I'm not mistaken this isn't actually spawning the new Centcomm at all?

**Comment by twinklezzzz** [comment]
ill go take a look at it

**Comment by twinklezzzz** [comment]
> If I'm not mistaken this isn't actually spawning the new Centcomm at all?

ill go take a look

**Pull request merged**
